name: 'PR: Build, Test & Analysis'

on: [ pull_request ]

jobs:
  pull_request_build_analysis:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, unit tests and slice tests with Maven
        run: mvn -B clean package -f pom.xml -Dtest='es.urjc.cloudapps.insurancecompany.unit.**'

      - name: Save Jacoco Exec
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage.exec
          path: target/jacoco.exec

      - name: Save Jacoco XML Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage_report.xml
          path: target/site/jacoco/jacoco.xml

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.projectKey='marcosDLCS_urjc_mca_ci_delivery' \
          -Dsonar.projectName='URJC MCA CI-DELIVERY' \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=marcosdlcs \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
