name: 'PR: Build, Test & Analysis'

on: [ pull_request ]

jobs:
  pull_request_build_analysis:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, unit tests and slice tests with Maven
        run: mvn -B clean package -f pom.xml -Dtest='es.urjc.cloudapps.insurancecompany.unit.**'

      - name: Save Jacoco Exec
        uses: actions/upload-artifact@v4
        with:
          name: jacoco_coverage.exec
          path: target/jacoco.exec

      - name: Save Jacoco XML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco_coverage_report.xml
          path: target/site/jacoco/jacoco.xml
