name: 'Release'

on:
  release:
    branches:
      - master

jobs:
  release_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Echo Release
        run: echo "Hello Release!"