name: 'Release'

on:
  release:
    branches:
      - master
    types: [ published ]

jobs:
  release_version:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, run all tests and package artifact with Maven
        run: |
          PROJECT_VERSION=$(mvn -B org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn -B versions:set -DnewVersion=$PROJECT_VERSION-RELEASE
          mvn -B clean verify -f pom.xml

      - name: Save Jacoco Exec
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage.exec
          path: target/jacoco.exec

      - name: Save Jacoco XML Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage_report.xml
          path: target/site/jacoco/jacoco.xml

      - name: SonarCloud Scan
        run: |
          mvn -B -f pom.xml sonar:sonar \
          -Dsonar.projectKey='marcosDLCS_urjc_mca_ci_delivery' \
          -Dsonar.projectName='URJC MCA CI-DELIVERY' \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=marcosdlcs \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
